apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-java-sample
spec:
  selector:
    matchLabels:
      app: gcp-java-sample
  template:
    metadata:
      labels:
        app: gcp-java-sample
    spec:
      containers:
      - name: gcp-java-sample
        image: hsh891230/gcp-java-sample:v1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: gcp-key
          mountPath: "/key"
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/key/pentacle-practice-bc9677900a95.json"
        - name: BUCKET
          value: hsh-bucket
      volumes:
      - name: gcp-key
        # configMap:
        #   name: gcp-service-account-key
        secret:
          secretName: gcp-service-account-key
