apiVersion: v1
kind: Service
metadata:
  name: gcp-java-sample-service
  labels:
    app: gcp-java-sample
spec:
  type: LoadBalancer
  selector:
    app: gcp-java-sample
  ports:
    - port: 80
      targetPort: 8080
  
