gcs-resource-post-bucket: ${BUCKET:}

spring:
  servlet:
    multipart:
      max-file-size: 10485760
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL55Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: ${DB_USERNAME}
    
  cloud:
    gcp:
      sql:
        enabled: true
        instance-connection-name: ${DB_INSTANCE_CONNECTION_NAME}
        database-name: ${DB_DATABASE_NAME}

---

spring:
  profiles: test
  jpa:
    database: h2
  cloud:
    gcp:
      sql:
        enabled: false
