gcs-resource-post-bucket: ${BUCKET:}

spring:
  servlet:
    multipart:
      max-file-size: 10485760
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: ${DB_USERNAME}
    
  cloud:
    gcp:
      sql:
        instance-connection-name: ${DB_INSTANCE_CONNECTION_NAME}
        database-name: ${DB_DATABASE_NAME}
